part of 'theme.dart';

class ADSTextTheme {
  TextTheme get theme => TextTheme(
        titleLarge: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 33,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
        displayLarge: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 24,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w700),
        displayMedium: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 22,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w700),
        displaySmall: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 16,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w700),
        headlineLarge: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 22,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
        headlineMedium: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 20,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
        headlineSmall: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 16,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
        bodyLarge: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 16,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w300),
        bodyMedium: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 13,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w400),
        bodySmall: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 12,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
        labelLarge: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 14,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w700),
        labelMedium: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 14,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w400),
        labelSmall: TextStyle(
            fontFamily: 'Overpass',
            fontSize: 12,
            color: ADSColor.textPrimary,
            fontWeight: FontWeight.w600),
      );
}
