name: ads_km7
description: "ADS Mobile Engineer - KM7"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  flutter_native_splash: ^2.4.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/Arial_Light.ttf
          weight: 300
        - asset: assets/fonts/arial/Arial_Regular.ttf
          weight: 400
        - asset: assets/fonts/arial/Arial_Medium.ttf
          weight: 500
        - asset: assets/fonts/arial/Arial_Bold.ttf
          weight: 700
        - asset: assets/fonts/arial/Arial_Black.ttf
          weight: 900
    - family: Overpass
      fonts:
        - asset: assets/fonts/overpass/Overpass-Regular.ttf
          weight: 400
        - asset: assets/fonts/overpass/Overpass-Bold.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/overpass/Overpass-Black.ttf
          weight: 900
        - asset: assets/fonts/overpass/Overpass-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/overpass/Overpass-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/overpass/Overpass-Light.ttf
          weight: 300
        - asset: assets/fonts/overpass/Overpass-Medium.ttf
          weight: 500
        - asset: assets/fonts/overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/overpass/Overpass-Thin.ttf
          weight: 100

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash-icon.png
  background_image: "assets/images/splash-background.png"
  android_12:
    image: assets/icons/splash-icon.png
    color: "#FFFFFF"
    background_image: "assets/images/splash-background.png"
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 16
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"
